# Generated by Django 3.2.9 on 2021-11-03 04:16

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=backend.models.generate_unique_code, max_length=8, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('company', models.CharField(max_length=150)),
                ('info', models.TextField()),
                ('top_selling', models.BooleanField(default=False)),
                ('favourite', models.BooleanField(default=False)),
                ('img', models.ImageField(default='../img/29118.jpg', upload_to='images/')),
            ],
        ),
    ]
