# Generated by Django 3.2.9 on 2021-11-04 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('laptops', 'laptops'), ('phones', 'phones'), ('accessories', 'accessories')], default='laptops', max_length=200),
        ),
    ]
